### ISSUE TITLE
After execute the code block, the caret should move to the next code block instead of next line

### ISSUE THREAD

**Issue by ntluong95** [guoci/pycharm-smart-execute#4]
After execute the first code block, the caret was in the red area. It should ignore the blanks lines and comment lines and jump directly to the next line where code can be implemented. See the picture below for more detail:
<img width="1009" alt="image" src="https://github.com/guoci/pycharm-smart-execute/assets/63569637/d8684e1b-6dfb-4a94-81f1-ee9be6d08633">

**Comment by guoci** [comment]
Is this the same as #3?
